###
GET http://localhost:8088/api/users

###
POST http://localhost:8088/api/users/create
Content-Type: application/json

{
  "name" : "Manoj M",
  "email":"manoj@gmail.com",
  "password" : "Manoj@14"
}

###
GET http://localhost:8088/api/users/1

###
POST http://localhost:8088/api/users/authenticate
Content-Type: application/json

{
  "email": "manoj@gmail.com",
  "password": "Manoj@14"
}

###
PUT http://localhost:8088/api/users/changePassword/1
Content-Type: application/json

{
  "oldPassword": "Manoj@14",
  "newPassword": "ManojM@14"
}

###
POST http://localhost:8088/api/admin/create
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@gmail.com",
  "password": "Admin@123"
}

###
GET http://localhost:8088/api/admin/1

###
POST http://localhost:8088/api/admin/authenticate/1
Content-Type: application/json

{
  "password": "Admin@123"
}

###
GET http://localhost:8088/api/medicines
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYW51bWFkaHUxNDI1QGdtYWlsLmNvbSIsImlhdCI6MTY5NDQzODk1MiwiZXhwIjoxNjk0NDc0OTUyfQ._4fDvH8DVFvtOE8HeTG-Zhvcrud8MOsEm54wyJnzU1Q

###
POST http://localhost:8088/api/medicines/create
Content-Type: application/json

{
  "name": "MedName",
  "price": 20.00,
  "seller": "MedSel",
  "description": "Desc",
  "image": {
    "fileName":"Medicine",
    "contentType": "image/png",
    "content": null
  }
}

###
PUT http://localhost:8088/api/medicines/update
Content-Type: application/json

{
  "id": 1,
  "name": "NewMedName",
  "price": 50.00,
  "seller": "MedSel",
  "description": "Desc"
}

###
GET http://localhost:8088/api/medicines/1

###
PUT http://localhost:8088/api/medicines/isenabled?enable=1

###
DELETE http://localhost:8088/api/medicines/delete/1

###
PUT http://localhost:8088/api/users/addToCart/1
Content-Type: application/json

{
  "email": "manoj@gmail.com"
}

###
PUT http://localhost:8088/api/users/removeToCart/1
Content-Type: application/json

{
  "email": "manoj@gmail.com"
}

###
PUT http://localhost:8088/api/users/purchase
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYW5vakBnbWFpbC5jb20iLCJpYXQiOjE2OTQ4NDQyMTMsImV4cCI6MTY5NDg4MDIxM30.oC_5a413yrO-qA56Ed4Yei9t-_ThSUvSi8a7qycZ-1A
Content-Type: application/json

{
  "email":"manoj@gmail.com",
  "medicineId": 1,
  "quantity": 1,
  "totalAmount": 300

}

###
PUT http://localhost:8088/api/users/purchases
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYW51bWFkaHUxNDI1QGdtYWlsLmNvbSIsImlhdCI6MTY5NTIwODA2MSwiZXhwIjoxNjk1MjQ0MDYxfQ.lcIJMz5QVzoFPypSup6iiKmNvv6gXUxjQo91UFafg9g
Content-Type: application/json

{
  "purchases": [
  {
    "medicineId": 1,
    "quantity": 1,
    "totalAmount": 300.0
  },{
    "medicineId": 1,
    "quantity": 2,
    "totalAmount": 600.0
  }
  ]
}

###
GET http://localhost:8088/api/users/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYW51bWFkaHUxNDI1QGdtYWlsLmNvbSIsImlhdCI6MTY5NDQzODk1MiwiZXhwIjoxNjk0NDc0OTUyfQ._4fDvH8DVFvtOE8HeTG-Zhvcrud8MOsEm54wyJnzU1Q